version: "3.9"

services:
  praetor-be:
    container_name: praetor-be
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5050:8443"
      - "5005:5005"
    environment:
      JAVA_TOOL_OPTIONS: >
        -Xmx128m -Xms64m -XX:+UseSerialGC
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    restart: unless-stopped
    networks:
      - praetor-net
    extra_hosts:
      - "local.aredegalli.it:host-gateway"

networks:
  praetor-net:
    driver: bridge
