version: "3.9"

services:
  praetor-be:
    container_name: praetor-be
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5050:8443"
    restart: unless-stopped
    networks:
      - praetor-net
    extra_hosts:
      - "local.aredegalli.it:host-gateway"

networks:
  praetor-net:
    driver: bridge
