spring:
  application:
    name: Praetor BE

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PRAETOR_DB_URL}
    username: ${PRAETOR_DB_USERNAME}
    password: ${PRAETOR_DB_PASSWORD}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  devtools:
    restart:
      enabled: false

  sql:
    init:
      mode: always

# SSL Config (HTTPS enabled with keystore)
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${PRAETOR_KEYSTORE_PASSWORD}
    key-store-type: PKCS12

# Logging
logging:
  level:
    root: WARN
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

# CORS Configuration (can be restricted per environment)
security:
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
  jwt:
    public-key: classpath:jwt/dominatus-public.pem
    expiration-time: ${PRAETOR_JWT_EXPIRATION}
  crypto:
    aes-secret-key: ${PRAETOR_AES_KEY}

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health, info, beans
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full

# HMAC
hmac:
  secret:
    key: ${HMAC_SECRET_KEY}

services:
  dominatus:
    base-url: ${DOMINATUS_BASE_URL}
  auctoritas:
    base-url: ${AUCTORITAS_BASE_URL}

